name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t zahramaslavi/docker-test -f Dockerfile.dev .
      - run: docker run -e CI=true zahramaslavi/docker-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: front-end
          environment_name: Front-end-env
          existing_bucket_name: elasticbeanstalk-us-east-1-670873404546
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
